#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App1.Resource", IsApplication=true)]

namespace App1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050010
			public const int azure = 2131034128;
			
			// aapt resource value: 0x7f050006
			public const int black_color = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int blue_color = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int colorAccent = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int colorPrimary = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int colorPrimaryDark = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int details_page_list_bg_color = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int disabled_color = 2131034124;
			
			// aapt resource value: 0x7f050008
			public const int grey_color = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int home_page_list_bg_color = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int light_blue_color = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int light_grey_color = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int lightest_grey_color = 2131034125;
			
			// aapt resource value: 0x7f050012
			public const int pageColor1 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int pageColor2 = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int pageColor3 = 2131034132;
			
			// aapt resource value: 0x7f05000e
			public const int tab_black_color = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int tab_selected_color = 2131034127;
			
			// aapt resource value: 0x7f050003
			public const int transparent = 2131034115;
			
			// aapt resource value: 0x7f050011
			public const int white = 2131034129;
			
			// aapt resource value: 0x7f050007
			public const int white_color = 2131034119;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int activity_horizontal_margin = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int activity_vertical_margin = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int big_text_margin = 2131099650;
			
			// aapt resource value: 0x7f060020
			public const int card_side_margin = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int card_zero_margin = 2131099681;
			
			// aapt resource value: 0x7f060023
			public const int config_button_width = 2131099683;
			
			// aapt resource value: 0x7f060022
			public const int config_top_margin = 2131099682;
			
			// aapt resource value: 0x7f06001f
			public const int date_time_margin = 2131099679;
			
			// aapt resource value: 0x7f060011
			public const int details_header_row_left_margin = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int details_row_left_margin = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int details_row_min_height_margin = 2131099663;
			
			// aapt resource value: 0x7f060012
			public const int details_row_start_margin = 2131099666;
			
			// aapt resource value: 0x7f060005
			public const int divider_list_margin = 2131099653;
			
			// aapt resource value: 0x7f060013
			public const int header_text_margin = 2131099667;
			
			// aapt resource value: 0x7f06001b
			public const int header_view_margin = 2131099675;
			
			// aapt resource value: 0x7f060007
			public const int image_min_height_margin = 2131099655;
			
			// aapt resource value: 0x7f060014
			public const int item_text_margin = 2131099668;
			
			// aapt resource value: 0x7f06000d
			public const int list_row_left_margin = 2131099661;
			
			// aapt resource value: 0x7f060006
			public const int list_row_min_height_margin = 2131099654;
			
			// aapt resource value: 0x7f06000e
			public const int list_row_right_margin = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int list_row_top_margin = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int main_row_top_margin = 2131099659;
			
			// aapt resource value: 0x7f06001a
			public const int progress_bar_margin = 2131099674;
			
			// aapt resource value: 0x7f060008
			public const int reset_image_height_margin = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int reset_image_width_margin = 2131099657;
			
			// aapt resource value: 0x7f06001e
			public const int row_gap_margin = 2131099678;
			
			// aapt resource value: 0x7f06001c
			public const int row_left_margin = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int row_right_margin = 2131099677;
			
			// aapt resource value: 0x7f060017
			public const int section_header_height_margin = 2131099671;
			
			// aapt resource value: 0x7f060015
			public const int section_text_margin = 2131099669;
			
			// aapt resource value: 0x7f06000a
			public const int settings_image_margin = 2131099658;
			
			// aapt resource value: 0x7f060004
			public const int small_text_margin = 2131099652;
			
			// aapt resource value: 0x7f060018
			public const int subsection_header_height_margin = 2131099672;
			
			// aapt resource value: 0x7f060016
			public const int subsection_text_margin = 2131099670;
			
			// aapt resource value: 0x7f060019
			public const int tab_row_height_margin = 2131099673;
			
			// aapt resource value: 0x7f060003
			public const int title_text_margin = 2131099651;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow_left = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow_right = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int plus_button = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int vessel_image = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000f
			public const int Empty = 2131296271;
			
			// aapt resource value: 0x7f09000e
			public const int SubmitClicked = 2131296270;
			
			// aapt resource value: 0x7f090009
			public const int UsersListView = 2131296265;
			
			// aapt resource value: 0x7f090000
			public const int action_bar_layout = 2131296256;
			
			// aapt resource value: 0x7f090008
			public const int activity_main = 2131296264;
			
			// aapt resource value: 0x7f090007
			public const int arrowImg = 2131296263;
			
			// aapt resource value: 0x7f09000a
			public const int configurationLayout = 2131296266;
			
			// aapt resource value: 0x7f090004
			public const int device_img = 2131296260;
			
			// aapt resource value: 0x7f090006
			public const int email = 2131296262;
			
			// aapt resource value: 0x7f09000b
			public const int emailText = 2131296267;
			
			// aapt resource value: 0x7f090001
			public const int name = 2131296257;
			
			// aapt resource value: 0x7f090003
			public const int notifyConfig = 2131296259;
			
			// aapt resource value: 0x7f09000d
			public const int passText = 2131296269;
			
			// aapt resource value: 0x7f090002
			public const int title = 2131296258;
			
			// aapt resource value: 0x7f090005
			public const int userName = 2131296261;
			
			// aapt resource value: 0x7f09000c
			public const int userNameText = 2131296268;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int custom_action_bar = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int list_row = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int list_view = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int LoginPage = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Main = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int email = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int email_hint = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int pass = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int user_name = 2131165186;
			
			// aapt resource value: 0x7f070005
			public const int user_name_hint = 2131165189;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int AppTheme = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int actionBarStyle = 2131230721;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
